server:
  port: 8086

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Microservicio de Animales
        - id: msvc-animal
          uri: lb://msvc-animal
          predicates:
            - Path=/api/animals/**
          filters:
            - StripPrefix=2

        # Microservicio de Adopciones
        - id: msvc-adoptions
          uri: lb://msvc-adoptions
          predicates:
            - Path=/api/adoptions/**
          filters:
            - StripPrefix=2

        # Microservicio de Finanzas
        - id: msvc-finances
          uri: lb://msvc-finances
          predicates:
            - Path=/api/finances/**
          filters:
            - StripPrefix=2

        # Microservicio de Salud
        - id: msvc-health
          uri: lb://msvc-health
          predicates:
            - Path=/api/health/**
          filters:
            - StripPrefix=2

        # Microservicio de PetShop
        - id: msvc-petshop
          uri: lb://msvc-petShop
          predicates:
            - Path=/api/petshop/**
          filters:
            - StripPrefix=2

      # Configuraci贸n global de CORS
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"

      # Configuraci贸n del descubrimiento de servicios
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

# Configuraci贸n de Eureka Client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: localhost

# Configuraci贸n de logging
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG